### ISSUE TITLE
Conflict with Ouijaboard keybind

### ISSUE THREAD

**Issue by KalmAndKollected** [Electric131/LCOuijaBoard#3]
Every time I press O in the terminal/console when typing it opens up the Ouijaboard UI and takes me out of the terminal.
Maybe disable the Ouijaboard when using the terminal or add a rebind option.

**Comment by Chepuxa** [comment]
Should be fixed in v1.3.1, but a keybind would still be nice

**Comment by Electric131** [comment]
This was a bug in v1.3.0, this should be patched in the latest version.
