### ISSUE TITLE
the ouija does not appear in the store.

### ISSUE THREAD

**Issue by renan55** [Electric131/LCOuijaBoard#6]
the ouija does not appear in the store. is configured to appear

**Comment by Electric131** [comment]
Works fine in testing, unless reproduction steps are provided there is no bug here. (Check for an incompatibility with other mods)

**Comment by renan55** [comment]
the mod is active, but Ouija does not appear in the store

**Comment by Electric131** [comment]
Again, seems to work fine for me so unless it's reproducible I'm going to close in ~12h to give time to respond.
