### ISSUE TITLE
Host communication problem with the board

### ISSUE THREAD

**Issue by Paradox75831004** [Electric131/LCOuijaBoard#7]
For some reason, in my build, I can't communicate through the board if I'm not the first to die. I haven’t figured out what the problems are, BUT others can take turns communicating without problems

Here is the code for our assembly:

LETHAL_LONERS - 018d11ff-0c74-f37b-b527-5d035dcab654

The test requires at least 2-3 people to understand what the problem is

Or I just went too far with the mods - then it might not be fixed...

**Comment by Electric131** [comment]
Not sure what the issue is just from a modlist alone, if you could send any kind of errors to track down the cause or conflicts that would be very helpful.

**Comment by Paradox75831004** [comment]
It doesn’t even show any information in the logs

**Comment by Paradox75831004** [comment]
Well I'll try to find something
