### ISSUE TITLE
The board works every other time

### ISSUE THREAD

**Issue by Paradox75831004** [Electric131/LCOuijaBoard#8]
Good afternoon, it's me again. The "O" key does not work immediately to speak through the board. Sometimes when I die first, I can use it, other players can't. Sometimes the opposite is true - I can't use it - and others do.

LETHAL_LONERS - 018d302e-6fc0-5322-4d5e-5fbf14cb27a5

**Comment by Electric131** [comment]
This is definitely some kind of conflict with some mod you have as I have never experienced or seen that bug happen.

**Comment by Paradox75831004** [comment]
Is there any way to find out in the console? What exactly is the problem

**Comment by Electric131** [comment]
Sorry for the very late response, thought I would at least say there might be errors in console or something untraceable through console alone. Try reproducing the bug then disabling mods until the issue is resolved.
